version: latest

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root!
    ports:
      - "27017:27017"
    volumes:
      - /Users/Pichau/Desktop/NewProjects/Volumes
    networks:
      - mongo-compose-network

  mongo-express:
    image: mongo-express:latest
    depends_on:
      - "mongo"
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: zortea
      ME_CONFIG_BASICAUTH_PASSWORD: MongoExpress2024!
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root!
      ME_CONFIG_MONGODB_SERVER: mongodb 
    links:
      - mongo
    networks:
      - mongo-compose-network
    

networks: 
    mongo-compose-network:
      driver: bridge